### PR TITLE
Fix autocorrect

### PR DESCRIPTION
**Pull request by galligan**
Trying to use [this method](https://davidwalsh.name/disable-autocorrect) to fix the problem.

### CODE REVIEW

**Comment by saulmc** [comment]
@galligan you'll want to remove the changes to `components/WalletProvider.tsx` that got copied over from the demo app

**Comment by galligan** [comment]
> @galligan you'll want to remove the changes to components/WalletProvider.tsx that got copied over from the demo app

@saulmc I'm not 100% certain but it seems like those changes are what are needed for the demo. Maybe @jazzz knows.

**Comment by saulmc** [comment]
They're needed for the demo fork, but merging them here will make the core app behave like the demo

**Comment by galligan** [comment]
@saulmc shit. This PR was supposed to go into the demo.

**Comment by jazzz** [comment]
This is the demo.xmtp.com as its in the Private Org.... isn't it

**Pull request closed without merging**
